name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: self-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Trivy Installation
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy
      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .
      - name: Gitleaks Installation
        run: sudo apt install gitleaks -y
      - name: Gitleaks Code Scan
        run: gitleaks detect source . -r gitleaks-report.json -f json

  test:
    runs-on: self-hosted
    needs: security-check
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Unit Test Cases
        run: mvn test

  build_project_and_sonar_scan:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Project
        run: mvn package
      - name: Generate Build Number
        run: echo "BUILD_NUMBER=$(date +%s)" >> $GITHUB_ENV
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
      - name: Checkout again for Sonar (fetch-depth 0)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build_docker_image_and_push_to_ECR:
    runs-on: self-hosted
    needs: build_project_and_sonar_scan
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names bankapp --region ap-south-1 || \
          aws ecr create-repository --repository-name bankapp --region ap-south-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image and Push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 054037106953.dkr.ecr.ap-south-1.amazonaws.com/bankapp:${{ env.BUILD_NUMBER }}
          file: ./Dockerfile

  deploy_to_kubernetes_with_argocd:
    runs-on: self-hosted
    needs: build_docker_image_and_push_to_ECR
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Checkout Helm or K8s manifest repo
        uses: actions/checkout@v4
        with:
          repository: your-org/your-argocd-deployment-repo
          token: ${{ secrets.GH_PAT }}
          path: deployment-repo
      - name: Update Image Tag in Manifest
        run: |
          sed -i 's|bankapp:.*|bankapp:${{ env.BUILD_NUMBER }}|g' deployment-repo/overlays/prod/deployment.yaml
      - name: Commit and Push Changes
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ env.BUILD_NUMBER }}"
          git push
